name: "GuithiumExample"
main: "net.pl3x.guithium.test.GuithiumExample"
version: "${version}"
api-version: "1.21.5"
description: "Guithium Example Plugin"
author: "BillyGalbreath"
depend:
  - Guithium

commands:
  anchors:
    description: Opens an anchors example
    permission: guithium.command.anchors
  calculator:
    description: Opens a calculator GUI
    permission: guithium.command.calculator
    aliases:
      - calc
  screen:
    description: Open the example screen
    permission: guithium.command.screen
