name: "${name}"
main: "${group}.${name}"
version: "${version}"
api-version: "1.19"
description: "${description}"
author: "BillyGalbreath"
depend:
  - ServerGUI

commands:
  screen:
    description: Open the test screen
    permission: servergui.command.screen
