name: "${name}"
main: "${group}.${name}"
version: "${version}"
api-version: "1.19"
description: "${description}"
author: "BillyGalbreath"
depend:
  - Guithium

commands:
  screen:
    description: Open the example screen
    permission: guithium.command.screen
