name: "${name}"
main: "${group}.${name}"
version: "${version}"
api-version: "1.19"
description: "${description}"
author: "BillyGalbreath"
depend:
  - Guithium

commands:
  calculator:
    description: Opens a calculator GUI
    permission: guithium.command.calculator
    aliases:
      - calc
  screen:
    description: Open the example screen
    permission: guithium.command.screen
